galaxy_info:
  author: DIALLO Abdoul Gadirou
  description: Apache installation using docker
  company: eazytraining.fr

   
  Licence: MIT
  

  min_ansible_version: 2.9

  
  
  platforms:
   - name: centos
     versions:
       - 7

  galaxy_tags:
    - webapp

dependencies: []
