all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
prod:
  hosts:
    client:
      ansible_host: ec2-44-202-34-116.compute-1.amazonaws.com
      ansible_ssh_user: centos
      ansible_ssh_private_key_file: /home/centos/ansible.pem

