---
- name: check distribution
  fail:
    msg: distribution must be centos
  when: ansible_distribution != "CentOS"

- name: Install EPEL repo
  package: name="{{item}}" state=present
  loop:
    - epel-release
    - git
    - wget
    - curl
    - python3
