---
- include_task: "setup.yml"
- include_task: "docker-install.sh"
  
- name: create index.html template
  ansible.builtin.template:
    src: ./templates/index.html.j2
    dest: ./index.html

- name: Create Apache container
  docker_container:
    name: webapp
    image: httpd
    state: started
    ports:
      - "{{external_port}}":"{{internal_port}}"
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
