---
- hosts: prod
  become: true
  vars:
    system_user: centos
  vars_files:
    - files/secrets/credentials-vault
  pre_tasks:
    - name : create www-data user i
      ansible.builtin.user: name=www-data state=present
  roles:
    - { role: AdnanHodzic.containerized-wordpress }
